### ISSUE TITLE
Planet Extractor Download failed

### ISSUE THREAD

**Issue by lines-off** [navit-gps/navit#1072]
I tried several times in the last weeks, every time the download fails few seconds after start.
I modified the trials
- big or small maps
- different regions
- different computers
- different operating systems.
At the moment I am not able to load maps for navit.

**Comment by marcelientje** [comment]
I have the same problem and on the navit wiki I got a 502 bad gateway message. Can you please look at these issues of this top product. It is unusable if we can’t download maps.

**Comment by jkoan** [comment]
Which link are you using? http://maps.navit-project.org is working for me

**Comment by marcelientje** [comment]
Thanks for your message. I see now what is going on. Some of the maps are not downloadimg. For imstance western europe and then Benelux did not work.

**Comment by martin-ac** [comment]
Hi, to me it looks like there are problems with Planet Extractor at "http://maps9.navit-project.org/" at least since map data have been updated to "map version 201101".

First kind of error I allways get is:
- I select the predifined area "Western Europe" and trigger the download with "Get Map!"
- next I get a page telling

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Serverfehler!

Die Anfrage kann nicht beantwortet werden, da im Server ein interner Fehler aufgetreten ist.

Fehlermeldung:
End of script output before headers: index.cgi

Sofern Sie dies für eine Fehlfunktion des Servers halten, informieren Sie bitte den Webmaster hierüber.
Error 500
maps9.navit-project.org
Apache/2.4.33 (Linux/SUSE) 
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

My translation to this is:
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Serverfailure!

The request cannot be answered because there was an internal server failure.

Errormessage:
End of script output before headers: index.cgi

If you think this is a malfunction of the server please inform the Webmaster.
Error 500
maps9.navit-project.org
Apache/2.4.33 (Linux/SUSE) 
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

I sent emails to the webmaster several times but didn't get an answer and the error persists.

In addition at all my systems (KUBUNTU 18.04, Firefox, Chromium, PC and two diffenent NB's, all did downloads without errors at least 12 months before) with every other kind of download I try I only get a few kbytes, then after less but 15 seconds an error message and then the download stops/hangs.
The error message in Firefox in this case is
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
/tmp/mozilla_....../1V602q2h.bin.part konnte nicht gespeichert werden, weil die Quelldatei nicht gelesen werden konnte.
Versuchen Sie es später erneut oder kontaktieren Sie den Server-Administrator.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
My translation to this:
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
/tmp/mozilla_....../1V602q2h.bin.part couldn't be saved because the source data are not readable.
Try again later or get in contact with the server administrator.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

To me it looks like currently nobody is able to get a download at Planet Extractor.
It would be great to get this working again - thanks a lot!
If you need someone for testing give me a hint.

P.S.: We shouldn't mix up failures: what I describe here imho is for current errors at Planet Extractor.
I do not think this has something to do with an error marcelientje describes: access to the old wiki at "http://wiki.navit-project.org/index.php/..." doesn't work but gives back "502 Bad Gateway". Think this should be handled separately?

**Comment by hoehnp** [comment]
I can confirm the conclusion of @martin-ac. Download via maps.navit-project.org seems to forward to two servers. maps9.navit-project.org does not work. I managed to download it finally via maps3.navit-project.org. The load balancing makes it sometimes appear to work.

**Comment by martin-ac** [comment]
Hi, three days ago - planet extractor showed "Map Version 201231" - I started another download session and have been able to download maps for predefined areas
Western Europe with 18061 MByte
Germany + Austria + Switzerland with 7324 MByte
Germany with 4427 MByte
Nordrheinwestfalen with 1157 MByte
now again without any problem during the download.

Maybe @marcelientje @hoehnp and @lines-off could doublecheck,
especially @lines-off for https://github.com/navit-gps/navit/issues/1012  to check if the case can be closed.

To me it  looks like the problem is fixed ...

**Comment by lines-off** [comment]
No more problem with download from Planet Extractor.
(by the way, #1012 is a different problem.)
