### ISSUE TITLE
Blank yellow map on Windows

### ISSUE THREAD

**Issue by tkamoua** [navit-gps/navit#1151]
### Thanks for opening an issue on Navit. Before submitting a bug report, please read the documentation on what to provide here:
https://wiki.navit-project.org/index.php/Reporting_Bugs

I downloaded the Win32 exe version of Navit from here: https://www.navit-project.org/. After I install and run it, the map is just a blank yellow map (attached image). . I have attached my navit.xml as a txt file. It seems that it should be using a sample map located at "$NAVIT_SHAREDIR/maps/osm_bbox_11.3,47.9,11.7,48.2.bin". I tried adding my own map using Navit planet extractor and placing the generated .bin file into a new folder called "maps" that I created in the "share" directory, then changing the map tag to be \<map type="binfile" data="$NAVIT_SHAREDIR/maps/mygeneratedbinfile.bin"\>, and finally I changed the "center" attribute of the "navit" element to the gps coordinates of my map. 

I would really appreciate any assistance in displaying a map in Navit. Some questions/potential causes I am thinking of are 
1) What directory is $NAVIT_SHAREDIR referring to?
2) Do I need to change the "center" tag to my new coordinates before I startup Navit for the first time, since after starting up Navit it will no longer use those center coordinates and instead display the last location before quitting the application? 
3) Why does the sample map of Munich, Germany not exist in my installation?

Thanks!

[navit.txt](https://github.com/navit-gps/navit/files/7148885/navit.txt)

![navit](https://user-images.githubusercontent.com/43224127/132969496-b39852a6-b723-430c-b67f-05b0476cc070.PNG)

**Comment by metalstrolch** [comment]
1 ) I don't know for sure where $NAVIT_SHAREDIR points on Windows platform as I never used Navit on Windows. You can probably find out by searching for navit.xml location. You can use "Settings->Maps" to check if your map was found by Navit at all. If it was found use town search to find any place on your map and show that.

2) When started, navit tries to load "center.txt" from shard dir containing the coordinates navit should point to after startup.
If this file is not present, it uses the "center" tag from navit.xml definition.
When Navit is quit, it writes out the current location to center.txt file.

So no, there is no need to update "center" tag on your navit.xml usually, as one just searchs for the correct position on the map and then closes navit. Navit then remembers the last position. "canter" in navit.xml is overruled by this.

3) It's disabled in build configuration because Windows build does not come with maptool, so we cannot generate it during build process. At least I thing that's why.

**Comment by tkamoua** [comment]
Thanks for the help. After following your guidance, I was able to get the map to show, as you can see in the first attached image. However, I'd like to have the interface present in the second attached image since the one I have right now is not very good for a car navigation system. Do you know how I can get the interface in the second attached screenshot? Thanks again. 
![my navit interface](https://user-images.githubusercontent.com/43224127/133169166-50ea4470-cc03-45f0-a579-d770c4ad72ac.PNG)
![navit navigation](https://user-images.githubusercontent.com/43224127/133169173-0c81b040-da7a-4a03-84bc-ed6c5c9c8643.PNG)

**Comment by metalstrolch** [comment]
Congrats it's finally working.
Only thing: you had bad luck on map downloading. The coastlines on OSM map were broken the time your map was generated so your area looks flooded. I'll try to fix that on OSM map, but that'll take some weeks to sneak in in the precalculated map repos.

The "3d" view can be enabled using "Settings->View->3d"

About the screen layout. The amount of buttons whatsoever on the screen is defined in the navit.xml file. Search for "osd type" in your navit.xml to find the buttons you see now.
But now we have the problem: Without knowing the source of your screenshot there's little chance to find the navit.xml osd configuration that produced it, But you can configure completely to your liking in navit.xml

**Comment by tkamoua** [comment]
Sounds good, everything looks great now (besides the flooding lol). For my project, I am going to try to implement custom routing into Navit (i.e specifying several points and creating a route between them, instead of just creating a route between start and destination). I will update if I have any more questions. Thanks again!

**Comment by jkoan** [comment]
> I'll try to fix that on OSM map, but that'll take some weeks to sneak in in the precalculated map repos.

Daily Maps can be downloaded from here: https://github.com/jkoan/gh-actions-mapserver/releases

**Comment by jkoan** [comment]
The Layout you wanted is a variant from this one: https://wiki.navit-project.org/index.php/OSD_Layouts#Netbook_Layout_2
