### ISSUE TITLE
The font on the map becomes a block

### ISSUE THREAD

**Issue by Guan-ji** [navit-gps/navit#1157]
As the title says, the GUI successfully displayed the map I downloaded. And the map was downloaded by using the mouse to select the area in OpenStreetMap. But the text on the map has become a block.
At first I guessed that the font was missing. After I installed the font on my ubuntu20, it still could not be displayed.

And I set <config xmlns:xi=............................. language="en_XX">(XX is my area) as stated in the official manual, but it didn't help.

**Comment by jkoan** [comment]
Could you please attach an image?

**Comment by Guan-ji** [comment]
> Could you please attach an image?

![9EDDAD65-47E1-4937-B6D7-0B9C44E88CF1](https://user-images.githubusercontent.com/56984759/134263204-d88ea5ae-02a9-4492-a2b1-37a18d49f92e.jpeg)

These squares are supposed to be words.

**Comment by mvglasow** [comment]
My first guess is that the font you are using lacks the characters needed to render the names.

* What character set should the names be in?
* What font are you using? (Which font did you install? Did you specify a particular font in your Navit config – if so, which?)
* What UI language are you using for Navit? Does it use the same character set as the names on the map? Do UI strings display correctly? (If you use English for the UI and the names on the map are in a script other than Latin, check the supplied map of Munich (~48°N 11°E) – do the names there display correctly?)

**Comment by Guan-ji** [comment]
I want to display **Chinese** on my map. And my UI successfully displayed **English**.
I used the `sudo apt-get install ttf-wqy-microhei` command to install the font, and when I typed `fc-list`, the output result has,
`/usr/share/fonts/truetype/wqy/wqy-microhei.ttc: WenQuanYi Micro Hei Mono,文泉驛等寬微米黑,文泉驿等宽微米黑:style=Regular`

This proves that I successfully installed the font.

My **navit.xml** file is configured as follows,
```
<layout name="Car" font="WenQuanYi Micro Hei Mono" active="1">
                        <layer name="streets">
                                <itemgra item_types="street_route_occluded" order="0-">
                                        <polyline color="#0000a0" width="20"/>
                                </itemgra>
                        </layer>
                </layout>
```

My navit GUI is set up as follows,
`Settings->Display->Layout `  checked **Car**

**Comment by mvglasow** [comment]
That looks correct to me, as described in the docs at https://navit.readthedocs.io/en/v0.5.6/configuration/index.html#defining-layers. My suspicion is that either expects the font name to be spelled differently, or the font selection does not work as expected.

Do you happen to have a map that has names spelled in Latin characters? (If not, the sample map of Munich should work, see above.) Then try the following:

* Remove the `font` attribute, do the names render correctly?
* Re-add the `font` attribute and set it to one of the Latin script standard fonts – Ubuntu Mono should do, the important thing is that you can tell when the new font is being used. When you now launch Navit, does it use the new font? If not, that indicates an issue with Navit’s font selection.
* If the above test indicated not general issue with font selection: As far as I know, WenQuanYi Micro Hei Mono has Latin characters as well. Try restoring `font="WenQuanYi Micro Hei Mono"` and check how Latin-script names are rendered (the difference to the standard font should be visible).
  * If Latin-script names render in a different font than WenQuanYi Micro Hei Mono, this indicates Navit cannot find (or use) the font for some reason, and is falling back to a different font.
  * If Latin-script names render in WenQuanYi Micro Hei Mono but Chinese-script names render as blocks, this would indicate some issues with the Chinese character set. Either Navit has trouble rendering Chinese characters, or the map encoding is faulty.

**Comment by Guan-ji** [comment]
> That looks correct to me, as described in the docs at https://navit.readthedocs.io/en/v0.5.6/configuration/index.html#defining-layers. My suspicion is that either expects the font name to be spelled differently, or the font selection does not work as expected.
> 
> Do you happen to have a map that has names spelled in Latin characters? (If not, the sample map of Munich should work, see above.) Then try the following:
> 
> * Remove the `font` attribute, do the names render correctly?
> * Re-add the `font` attribute and set it to one of the Latin script standard fonts – Ubuntu Mono should do, the important thing is that you can tell when the new font is being used. When you now launch Navit, does it use the new font? If not, that indicates an issue with Navit’s font selection.
> * If the above test indicated not general issue with font selection: As far as I know, WenQuanYi Micro Hei Mono has Latin characters as well. Try restoring `font="WenQuanYi Micro Hei Mono"` and check how Latin-script names are rendered (the difference to the standard font should be visible).
>   
>   * If Latin-script names render in a different font than WenQuanYi Micro Hei Mono, this indicates Navit cannot find (or use) the font for some reason, and is falling back to a different font.
>   * If Latin-script names render in WenQuanYi Micro Hei Mono but Chinese-script names render as blocks, this would indicate some issues with the Chinese character set. Either Navit has trouble rendering Chinese characters, or the map encoding is faulty.

When I set as follows,
```
<layout name="Route" font="WenQuanYi Micro Hei Mono" active="1">
                        <layer name="streets">
                                <itemgra item_types="street_route_occluded" order="0-">
                                        <polyline color="#0000a0" width="20"/>
                                </itemgra>
                        </layer>
                </layout>
```
And when I set `Setting->Display->Layout->Route` on the map I downloaded, my GUI font became **WenQuanYi Micro Hei Mono**. But my map did not originally have the Route layout, so I saw the yellow screen.



And when I set as follows,
```
<layout name="Car" font="WenQuanYi Micro Hei Mono" active="1">
                        <layer name="streets">
                                <itemgra item_types="street_route_occluded" order="0-">
                                        <polyline color="#0000a0" width="20"/>
                                </itemgra>
                        </layer>
                </layout>
```
 `Setting->Display->Layout->Car`, At this point I can see the map, but the font on the map and the font of the GUI have become the **default fonts**.

So I guess there is no problem with my font. It may be a problem with the Layout configuration in the navit.xml file.
Could it be the reason for `<layer name="streets">`?    If this is the reason, then how do I know the **layout_name** of the map? 
Because I have the following options in `Setting->Display->Layout`: Bike, Car, Car-Android, Route...
Should I configure them separately in navit.xml?

**Comment by mvglasow** [comment]
> But my map did not originally have the Route layout, so I saw the yellow screen.

Maps know nothing about layouts. Maps contain items of different types (roads of different classes, waterways, landuse polygons, buildings etc.), and the layout tells Navit how to render them. Some layouts may render only certain item types, and (in theory) some maps may exclude certain less relevant item types. However, the most common ones should be found in every map and every layout, thus incompatibilities between map and layout are not really an issue in practice. However, IIRC `Route` renders only the route, no other map objects, so you would get just the map background when not in routing mode (same here, just tried it).

> how do I know the **layout_name** of the map?

When you choose a layout from the GUI, the name is the `name` attribute of the layout.

Judging from your attempts with the route map, font selection should work and you are using the correct name to refer to the font.  My suspicion is that Navit is using a different layout than you think it is. To test, pick an `itemgra` for a common item type, preferably with an `order` of `0-` (i.e. rendered at all zoom levels), and change its color. Restart Navit and choose the layout you modified, and see if your color changes are reflected. If not, Navit is not using the layout you thought it was.

We recently (last 1–2 years) made some additions to allow keeping layouts in files separate from navit.xml, and allow a mix of predefined and user-defined layouts. I don’t remember the exact details, but there is some potential for name collisions (two layouts with the same name defined in two places), and I don’t know off the top of my head how Navit resolves that. A name collision would explain why changes to your layout do not take effect. To test if that is the case, simply give the layout you modified a different name (e.g. `Car-Custom` instead of `Car`). Does a layout with the new name appear in your list the next time you start Navit? When you choose it, do your changes take effect?

**Comment by Guan-ji** [comment]
Thank you, I solved this problem. The solution is to directly modify **navit_layout_car.xml** instead of **navit.xml**
