### ISSUE TITLE
error reading /home/user/.navit/navit.xml

### ISSUE THREAD

**Issue by mrakyhub** [navit-gps/navit#1246]
error:navit:main_real:error reading config file ̈́/home /user/.navit/navit.xml':Element 'config' within unexpected context 'mapset'. Expected '' at line 10, char 1
 at line 417, char 51

error:navit:main_real:Chyba při načítání konfiguračního souboru '/home/user/.navit/navit.xml': Element 'config' within unexpected context 'mapset'. Expected '' at line 10, char 1
 at line 417, char 51

**Comment by adevoss** [comment]
Isn't that a typo in your navit.xml?
Please try the example navit.xml that is provided by navit.

My mapset tag only contains map tags. And only one mapset can be enabled.

**Comment by mrakyhub** [comment]
i try a original file navit.xml, and same error.  when i go to lines 10 and 417, i cant find any bad chars. i think that error will be somwhere around.

**Comment by adevoss** [comment]
Try an xml validator.

**Comment by mrakyhub** [comment]
I try xml  validator, add navit.dtd, and no errors.

**Comment by jkoan** [comment]
Please upload your navit.xml and the log output of navit here.

**Comment by pauruiz** [comment]
Found a similar error due to the automatic include of xml files from the maps folder, maybe that is the reason davit.xml was correct, and also that the log shows message about maps... (This shows even if that is configured as disabled [I reckon xml must be totally correct, even if later navit does not use it]), so I reckon that may be a feature, not a bug
