### ISSUE TITLE
Autozoom disables Northing and 2D mode

### ISSUE THREAD

**Issue by AchimStuy** [navit-gps/navit#1270]
First, thank you for creating such a great open source navi app!

I am using Navit on a Win CE car radio (from Zenec, if that matters). And I would like to have a traditional map view, meaning 2D and oriented north. `orientation="0"` and `pitch="0"` are working fine, as long as I don't enable `autozoom_active`. But as soon as I enable autozoom (either manually in the navit.xml or via OSD / menu config) I get the kind of first person view with some pitch and map oriented in driving direction. A similar issue is described in [#1235](https://github.com/navit-gps/navit/issues/1235#issuecomment-1553750754).

Is that a bug or a feature? Can I somehow enable autozoom and keep 2D view and northing?

**Comment by freecycler** [comment]
I suspect it is as gefin said here: 
https://github.com/navit-gps/navit/issues/1235#issuecomment-1549743759

`There are some automatic settings in navit.xml which overwrite your changes. You can use your own navit.xml to change this automatics.`

you likely need to edit navit.xml. Search it for the line (only 1 instance roughly halfway through the file) containing "pitch=autozoom" to to see what makes these settings conditional on autozoom. I never did find out what the reason for that was, I am guessing some early user/dev wanted that setting and it ended up getting copied into production releases a long time ago and the reason forgotten (ie, a bug). I certainly consider this linkage to  be an anti-feature.

Since I always turn northing off, I have not tried to adjust this line myself. By any chance are you setting follow to 0 ?

**Comment by AchimStuy** [comment]
That makes sense. I deleted the line from the `navit.xml` and it's working now. Thanks!
