### ISSUE TITLE
Nonexisting Bridge still shown

### ISSUE THREAD

**Issue by Eldkatten** [navit-gps/navit#1273]
Hello.

A bridge on the A544 (Aachen, Germany) at 50°47'29.6"N 6°08'05.2"E is permanently demolished and the A544 will not be connected to A4 etc for at least three years. This is shown in the current maps (OSM, Planet Extractor). Though, when I download the newest maps and use them in Navit, the route lead through that non-existant bridge nevertheless.
Is this an issue with the map or with navit? How can I fix it?
I use Navit version 0.5.6.arm64-v8a on Android 10
 
Thank you for your help.

**Comment by jkoan** [comment]
Hi @Eldkatten 
From what I see at http://maps3.navit-project.org/ the map version is 220714 which means last updated on 14. July 2022 so the OpenStreetMap Data is from that date. The problem is that none the current navit team has access to those old map servers. As a replacement I built this:  https://github.com/navit-gps/gh-actions-mapserver/releases/latest
Here you should find regularly updated maps. The only downside is that you can't download a self defined area, only those that are available. 

 Please respond to let us know if this helps.

**Comment by Eldkatten** [comment]
Hello @jkoan,
thanks a lot, the gap is there now 😃

Unfortunately, navit now seems to be unable to calculate the route, the calculation is stuck showing the "no route available sign":
![Screenshot_20240901-143318](https://github.com/user-attachments/assets/244100ed-6078-4968-9bb3-68751271906b)

**Comment by Eldkatten** [comment]
Addition to my previous post: if I set my location manually _in the vicinity of my actual position_ , the route calculation works fine and fast. I'll figure it out, I can live with the ristriction that the route is calculated when I'm already on my way.

Thanks alot for your help

**Comment by Eldkatten** [comment]
And once more, sorry: it seems that Navit knows now, that this short part of the A544 isn't usable (in reality the whole "autobahn" and the ramps are closed), so it still tries to calculate a route as close as possible to the route which would be valid including that bridge. Which doesn't work actually.
I have no idea how to fix this, I'll try this evening if it really works when I'm on the way.

**Comment by jkoan** [comment]
Please check what the data on osm is like as well. If it's wrong there there isn't anything we can do about it. 
The only thing we could do some day is traffic. You said the ramps and Autobahn is closed. These are traffic events. @mvglasow already implemented traffic via  https://traffxml.gitlab.io/ (which he designed). Also I recently looked into https://mobilithek.info/ where Germany provides a lot of data sets including Sets from the Autobahn GmbH which should include such closures. But so far this is in its research phase.

**Comment by mvglasow** [comment]
The fact that there used to be a stretch of road which is now gone, or that a stretch of road is currently impassable, would be treated just as if there had never been a road.

Navit uses the LPA* algorithm for routing, which is an evolution of the Dijkstra algorithm. It builds a network of nodes (start position, destination and every point in which the driver has a choice between two or more roads) and vertices (links between nodes). Each vertex is assigned a cost, based on the time it takes to travel along it, and Navit looks for the cheapest link between start and destination. If a road segment is impassable, its cost is infinite; if a road segment is removed, so it the vertex between its two end points. Due to the way Dijkstra and LPA* works, vertices with infinite cost never get considered for routing – it is as if there was no road between these two nodes.

However, Navit does simplify the graph it builds from the map: lower-class roads (iirc primary and below) only get considered in the immediate vicinity of the start location and destination. For long-distance routing, only motorway and trunk roads get considered. If the only way to reach your destination includes leaving the motorway/trunk network and using lower-grade roads, Navit may send you on a huge detour or even fail to find a route.

The decision to implement it this way was made some 15+ years ago, when device memory was much more constrained.

You could work around this by changing the route profile (in the `vehicleprofile` you are using) to include `primary`. We used to have docs for this, but they were in the old wiki and I don’t know where they ended up. Depending on what road the preferred detour includes, you might need to include even lower road classes.

@jkoan from the screenshot it looks as if the segments were deleted or retagged `highway=construction` or similar. In this case Navit would know not to use the closed part of the road and we wouldn’t need any more traffic events.

**Comment by Eldkatten** [comment]
Thank's ya'll for your time and effort. Obviously outdated map dates where the reason for other issues for me in the past as well. It works a lot better and faster now.
I'm on my way to a concert this evening and will try out how navigation works now. Looks very well so far. I'll have a look at the suggestions you made later this week.

Again, thanks a lot 😃

**Comment by Eldkatten** [comment]
Hello again,

navigating with the new current mapfiles went very well yesterday.
Though there seem to be a few flaws in the map data, like unconnected roads which in reality are perfectly accessible. Maybe it's the interpretation of map data, which is the problem, but I don't think it's Navit's fault.
I attach some screenshots of kind of erratic routes calculated while I was approaching the actual street I live in. Maybe the problem is that that street, like at least parts of the surrounding streets, are declared as "Bicycle Road" (german "Fahrradstrasse"), with elevated rights for bicycles, but where motorized vehicles like cars are allowed as "guests", with certain restrictions like speed limits. It looks like Navit tries to avoid those streets as much as possible. Maybe that's also the cause why route calculations from my home prosition fail with the new map data, but succeed when I move my location somewhat away from those streets.

Anyway, I don't think there's a need for action, and again thanks a lot for providing the new map data 😊

![Route_01](https://github.com/user-attachments/assets/a319ce66-2037-4d73-894d-3889db5918cb)
![Route_02](https://github.com/user-attachments/assets/64829fb6-1b48-46f1-856c-78d6ea5fc177)
![Route_03](https://github.com/user-attachments/assets/4bb9ab94-bc1a-4802-99c7-507cfda90258)

**Comment by Eldkatten** [comment]
Maybe I should mark this thread as "solved" or something?
