### ISSUE TITLE
Status of the support of Garmin files

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#16]
Hi guys,

In https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=601135 Mouarfffff was trying to use Garmin images but wasn't able to do it successfully.

In the changelog I see that the Garmin files support is being worked on. Do you have a Milestone about this?

Thanks
Joseph

**Comment by sleske** [comment]
Hi, the move to GitHub is quite new, so things are still being worked out, but we'll probably keep the issue tracker at http://trac.navit-project.org/ . Could you please file your bugs over there? Thank you!

**Comment by pini-gh** [comment]
Hi,

What is the reason for closing this issue? Garmin support improved or "please use http://trac.navit-project.org/"?

Thanks,

**Comment by sleske** [comment]
Yes, I closed the issue because I was under the impression we still use trac. However, it seems there is a discussion, so maybe that was premature.

Anaway, I can answer your question:

As far as I'm aware, noone is working on Garmin support, and there is no milestone. The Garmin code has not had seen work for several years, and except for the Debian bugreport I have not heard of someone who needs it. Also, the problem is that there are several variants of Garmin files (see Debian bug above for details), and some are not even documented, so it's unclear whether it's possible to support them.

So I hope that answers your question.

If you have a specific file that you want to use, please file a separate issue (here or on trac, we'll see), then _maybe_ we can get it to work. But as explained, the answer will probably be no, unless someone steps up to work on it. Sorry.
