### ISSUE TITLE
[Proposal] Nightly build channel

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#366]
Putting that here as it's not a bug, just a follow up from #355 .
I was wondering what kind of stuffs we would need for a nightly build channel.
I have a raspberry pi 2 I could lend as a buildbot if it can help.
How do you guys want to proceed?

**Comment by jkoan** [comment]
Hi @aerostitch I would think it should be not to hard to provide beta channels. First step would be to discuss for what platforms we want to provide beta channels.
My suggestion would be
1) fdroid (own additional repo which could be added to fdroid app)
2) debian/ubuntu ppa
3) repo for RPM (I am personally don't know about what we need to do there, but we will find out)

Then and in my mind this is the most difficult part (because I don't know about our server infrastructure) is to set up the repositorys and provide a way for circleci to push them to on the server. The server should then rebuild index or what ever is needed. About the server we need the help of @pgrandin 
In total this should not be really hard to setup

**Comment by aerostitch** [comment]
Turning that into a project so we can have separate tasks and everyone can take one: https://github.com/navit-gps/navit/projects/3
