### ISSUE TITLE
Altitude still in Meters w/Imperial

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#535]
When Imperial \(imperial="1"\) is loaded in the xml file, all measurements appear to correctly be in Imperial EXCEPT the ALTITUDE, which is still in meters.

Reported by: *anonymous

Original Ticket: [navit/bugs/46](https://sourceforge.net/p/navit/bugs/46)

**Comment by charlescurley** [comment]
Do you know where this occurs? I may have gotten it with the changes I made last fall.

**Comment by aerostitch** [comment]
I'm not sure. I am only the reporter because I migrated the issues from sourceforge in bulk.
The bug was filed on sourceforge 6 years ago so it might have been fixed since then (that's why it has the "needs-triage" label.
If you can't reproduce it I'll close it.
Thanks! :)

**Comment by charlescurley** [comment]
I think it was in the status bar at the bottom of the GTK window. I vaguely recall fixing that. Anyway, as soon as my GPS receiver warms up I'll confirm.

**Comment by charlescurley** [comment]
Yep, I confirm I get feet in the status bar. The numbers are right for where I am. Feel free to close.

**Comment by aerostitch** [comment]
Perfect, thanks a lot! :)

**Comment by espresso0000** [comment]
I have the same problem, imperial changed speed to mph but Altitude still displays meters for me, how to change this?

**Comment by charlescurley** [comment]
On Sat, 08 Jun 2019 15:47:31 -0700
espresso0000 <notifications@github.com> wrote:

> I have the same problem, imperial changed speed to mph but Altitude
> still displays meters for me, how to change this?

Hmmm. I don't know what you are looking at. The work I did was on the
GTK interface, as of commit 1d104b283248c3f45096618c58bef8429d37bcf,
Sat Dec 2 03:47:19 2017 -0700. So you will need a version as of that
date.

I just fired up my most recent build, as of commit
cc781eec9b8825d1ffbbb4798e2b86ac2d08be62, Tue Mar 5 16:26:59 2019
+0100, and I see altitude displayed in feet.

I am looking at the status bar, at the bottom of Navit's window.
Altitude is shown between the longitude and the track (course made
good). The traditional indicator for feet, a single quote, is right
after the value.

-- 
"When we talk of civilization, we are too apt to limit the meaning of
the word to its mere embellishments, such as arts and sciences; but
the true distinction between it and barbarism is, that the one
presents a state of society under the protection of just and
well-administered law, and the other is left to the chance government
of brute force."
- The Rev. James White, Eighteen Christian Centuries, 1889
Key fingerprint = CE5C 6645 A45A 64E4 94C0  809C FFF6 4C48 4ECD DFDB
https://charlescurley.com

**Comment by espresso0000** [comment]
There is a chance it is displaying at yards instead of feet, just installed yesterday would think is the latest version of navit and the on screen display.  I will snap a screen show of what I am looking at in just a few.
Chris

Sent from Yahoo Mail on Android 
 
  On Sun, Jun 9, 2019 at 12:53 PM, Charles Curley<notifications@github.com> wrote:   On Sat, 08 Jun 2019 15:47:31 -0700
espresso0000 <notifications@github.com> wrote:

> I have the same problem, imperial changed speed to mph but Altitude
> still displays meters for me, how to change this?

Hmmm. I don't know what you are looking at. The work I did was on the
GTK interface, as of commit 1d104b283248c3f45096618c58bef8429d37bcf,
Sat Dec 2 03:47:19 2017 -0700. So you will need a version as of that
date.

I just fired up my most recent build, as of commit
cc781eec9b8825d1ffbbb4798e2b86ac2d08be62, Tue Mar 5 16:26:59 2019
+0100, and I see altitude displayed in feet.

I am looking at the status bar, at the bottom of Navit's window.
Altitude is shown between the longitude and the track (course made
good). The traditional indicator for feet, a single quote, is right
after the value.

-- 
"When we talk of civilization, we are too apt to limit the meaning of
the word to its mere embellishments, such as arts and sciences; but
the true distinction between it and barbarism is, that the one
presents a state of society under the protection of just and
well-administered law, and the other is left to the chance government
of brute force."
- The Rev. James White, Eighteen Christian Centuries, 1889
Key fingerprint = CE5C 6645 A45A 64E4 94C0 809C FFF6 4C48 4ECD DFDB
https://charlescurley.com
