### ISSUE TITLE
Write real traffic plugins (which connect to live traffic sources)

### ISSUE THREAD

**Issue by jkoan** [navit-gps/navit#588]

**Comment by jkoan** [comment]
For NRW in Germany I found some really nice sources:
https://open.nrw/dataset/verkehrszentrale-verkehrslage-los-1476688071631
A lot of data in encoded with the datex2 standard could be useful.

Here is the actual date for that region, so it could probably become a good staring point for a plugin:
https://open.nrw/broker.mdm-portal.de/BASt-MDM-Interface/srv/2875002/clientPullService?subscriptionID=2875002

**Comment by pgrandin** [comment]
Maybe this is a bit too vague for an issue? I'm concerned that this might stay open for a while.

**Comment by mvglasow** [comment]
I see your point, but the only way to add comments to an item in a project dashboard seems to be converting it into an issue. We could handle this one restrictively, e.g. by closing it once the traffic branch is merged and we have at least one functional plugin. Further plugins would then be feature request, with one issue per plugin.

**Comment by pgrandin** [comment]
Works for me. I just want to avoid having issues open for like 6 months :)

**Comment by mvglasow** [comment]
a17b553 adds a (still non-functional) skeleton for an Android plugin, which will be able to receive TraFF feeds.

My Qz project has been extended to send TraFF feeds upon receiving new messages. This is not yet in a released version, as the Android intent names are not yet final. I also have a test app at https://gitlab.com/mvglasow/traff-test, which can receive TraFF feeds and display their XML data, or send a hardcoded TraFF message (useful for testing if you have no TMC hardware).

Expect more to come over the next few weeks.

**Comment by mvglasow** [comment]
As of 9968bdb, traffic support is functional but still experimental. With the current build of Qz (https://gitlab.com/nvglasow/qz), a supported TMC dongle and in a supported TMC reception area (see the Qz wiki for details), Navit now picks up traffic reports and routes around congestions.

If you don’t have the necessary prerequisites for live traffic, you can use `traff-test` (see link above) to send a static message (or adapt the program to send whatever message you would like it to send). Note that the current version of Qz no longer responds to poll requests (which Navit sends on startup); if you want Navit to process a message, you have to explicitly send one.

In any case, don't forget to add `<traffic type="traff_android">` to `navit.xml` (this is currently not in the default configs), else you will never get any traffic messages.

Previous builds have experienced crashes on certain messages, which I ascribe to making some assumptions in the code which turned out to not always hold true for real-world messages. I have attempted to fix these but cannot tell for sure if this has fixed the problem (I might just not have picked up any more problematic messages).

To debug this, set the debug level for `traffic_traff_android` to 3. This will dump each feed to the log before attempting to decode it. If Navit crashes, examine the last feed before the crash.

The one thing that will definitely need to be changed is the Android intent names: currently I am using some from my personal namespace; I am planning to move these to a more generic namespace. When that has happened and the traffic plugin has proven stable, I am planning to close this issue.

**Comment by mvglasow** [comment]
Two stability improvements today:
* Fixed a condition which would cause crashes on certain messages (and only after the second occurrence)
* If multi-event messages have a mixture of invalid/unknown and valid events, the valid parts are processed (previously the whole message would get discarded and valuable information lost)

**Comment by mvglasow** [comment]
Another fix: if no matching segments are found for a traffic message, at least that won’t crash Navit anymore. Still figuring out why we’re not finding any segments, though…

**Comment by mvglasow** [comment]
We now have a final domain, `traffxml.org`, to use as a base name for TraFF-related broadcasts. 6d9c9392 switches to the final names; the latest commits of Qz and TraFF Test have it as well, thus the whole existing TraFF ecosystem is now compatible (again). Please be sure to upgrade everything at once, as there is no backward compatibility.

**Comment by mvglasow** [comment]
The traffic module has proven stable in the last few weeks, with no more crashes. I am therefore closing this issue.

If anyone wants to help out, feel free to contribute traffic modules. The approach I’ve taken for Android is to write a generic plugin which takes feeds in TraFF format, sent as Android broadcasts. The actual interfacing with traffic sources is done by dedicated apps such as Qz—this allows other navigation (or other) apps to benefit from traffic information as well, and decouples Navit from the different sources users might wish to use. I would recommend the same approach for other platforms—on Linux, something similar could be done using Dbus.

For a description of the TraFF format, head over to https://traffxml.gitlab.io/.

**Comment by mvglasow** [comment]
> For NRW in Germany I found some really nice sources:
> https://open.nrw/dataset/verkehrszentrale-verkehrslage-los-1476688071631
> A lot of data in encoded with the datex2 standard could be useful.
> 
> Here is the actual date for that region, so it could probably become a good staring point for a plugin:
> https://open.nrw/broker.mdm-portal.de/BASt-MDM-Interface/srv/2875002/clientPullService?subscriptionID=2875002

Just revisiting this one for another TraFF source (RoadEagle), which works with online data and converts them to TraFF. Currently only for Poland and Lithuania, but I am working on a Datex 2 plugin at the moment (which will add support for a bunch of sources across Europe). I am gathering data sources at https://gitlab.com/traffxml/roadeagle/wikis/Data-Sources. If you have anything else (not necessarily Datex 2), pointers would be appreciated!
