### ISSUE TITLE
COPYING doesn't contain a license

### ISSUE THREAD

**Issue by yurivict** [navit-gps/navit#779]

**Comment by pgrandin** [comment]
Thanks for the report @yurivict 

The COPYING file currently list the 2 licences that we have been using (with typos that we'll fix via https://github.com/navit-gps/navit/pull/787/files ) and the licenses are provided in their own files.

Do you have an example that we should follow for better clarity? 
Googling for inspiration didn't really help because of terms like "copying" :)
