### ISSUE TITLE
Qt5 GUI

### ISSUE THREAD

**Issue by viktorgino** [navit-gps/navit#790]
What are the plans for the Qt5 QML GUI? I'm planning on using Navit for my project and as a part of that I'm planning on creating a QML based UI. Would there be interest for that here as I'm happy to contribute it back as I go along?

**Comment by metalstrolch** [comment]
I don't think there are any "plans" left.
While of course a native qt5 QML UI is likely demanded,
There is a only Qt5 QML proof of concept on which development has stalled since some time unfortunately for reasons I don't know. At least it still builds and is somewhat functional, but far from complete.

Feel free to base your work on that, and of course feel free to contribute. If you need any help don't hesitate to ask.

**Comment by hoehnp** [comment]
The Qt5 ui is used as far as I know in our port for Sailfish OS. I think when we were trying to get navit run on Sailfish OS we last looked at this gui. But I am not sure about it. For sure, help on the QML UI is highly appreciated. Also from me.

**Comment by viktorgino** [comment]
Thank you both for your reply.

I will slowly start working on this, can I keep this issue open to post updates in?

**Comment by pgrandin** [comment]
Hi @viktorgino !

@hoehnp I think that Sailfish OS is using the qt5 driver, but not the gui (at least I hope so, because the gui isn't finished yet :) )

I think that it would be great to get some help on the QT5 QML gui.
We also started gathering ideas about how to organize the menu content to make it more intuitive in this repository : https://github.com/navit-gps/navit-gui-qt5, feel free to contribute!

It would probably be a good idea to chat about the current state of things and what you want to do for your own project. You can reach us via our IRC channel irc://irc.freenode.org/navit or via Discord : https://discord.gg/ADfXxZx

Regarding keeping this issue open, I think that it makes sense until we can get the ball rolling, but maybe we should close it soon once you get started as it isn't really actionable as-is.

**Comment by hoehnp** [comment]
@pgrandin: generally Sailfish OS uses QML based qt5 guis. That's why I assume it is also the case for the Sailfish port, but I will check if I find something in our build script.

**Comment by hoehnp** [comment]
@pgrandin: if you check here: https://github.com/navit-gps/navit/blob/4b732b5b0adedbd27f5d01d6002a5a5cb1f89ec7/contrib/sailfish/navit-sailfish.spec#L26
I am pretty certain that it uses the qt5 gui, otherwise all these build requires would not make any sense.

**Comment by metalstrolch** [comment]
The Sailfish build contains the QT5 QML gui, but does not use it by default. It uses the internal gui.
I once added the qml gui to the default build, as I hoped to see more progress here and it was based on my qt5 graphics work. But as we all know it stalled. You can enable it on sailfish by changing the navit.xml as usual.

Sailfsih and QML is indeed a special story, as Sailfish would expect us to use Sailfish specific proprietary QML widgets (Silica), which would require additional porting and are compatible to nothing except Sailfish. But I never tried to really get Navit into Sailfish official harbour.

**Comment by pgrandin** [comment]
Well hopefully with @viktorgino 's help and a few other people chiming in we can revive the effort on the QT5/QML2 GUI, that would be neat!

**Comment by pgrandin** [comment]
@viktorgino this issue doesn't really seem actionable. Now that you have a good grasp on the code and started pushing some work in a branch, can we close it?

**Comment by viktorgino** [comment]
@pgrandin agreed
