### ISSUE TITLE
Maps from planetextractor render slow on weak devices.

### ISSUE THREAD

**Issue by gefin** [navit-gps/navit#894]
After installing a actual nightly navit  and a new map from planetextractor rendering is very slow (4 sec). Device is a Tomtom730 with 64MB

The test map from PR #861 bayern.bin (multyplygon w holes ) render quick (<0.5 sec)
A map built with actual maptool work also well. Multipoligons with holes work with it well. 

To make the planetextractor map to work better I need a cache_size >15000000. Other maps need only 6000000.

Was at planetextractor  a change except multipolygon?  I remember to read something with 64 bit.

**Comment by metalstrolch** [comment]
Oh, I didn't notice the maptool for the planet extractor was updated.

One major difference between anything from planet extractor and the "bayern.bin" i provided is the fact that I just processed a small portion (Bavaria) out of osm, so nothing was shifted up in the higher tiles as for example nothing crossed the equator of course.

Extracting something from planet always keeps the higher tiles with everything inside. So for example even if you just extract bavaria from planet.bin, you'll get everything crossing equator for example. You can check on your device by zooming out until you see almost all of the world.
Do the same with my bayern.bin and there will be nothing.

Of course with the multipolygon patch, there will be way more objects crossing those high tile lines that will be processed even if you only extracted a really small portion of the world. This is currently a limitation of how we extract portions from planet.bin.

Do you still have an "old" excerpt? I think my "bayern.bin" will be faster than any pre-multipolygon planet extractor excerpt? Can you check this?

I've some ideas how to overcome this, for example by cutting elements crossing equator to pipe them more down. But it'll require me some time to investigate.

Btw: I think this is linked to #873

**Comment by metalstrolch** [comment]
Switching to 64bit zip shouldn't change anything as your excerpt always has been 64bit. The bayern.bin is a 64bit zip as well. Planet.bin is larger than 4GiB requiring 64bit zip file for ages. Only the option to switch for 64bit zip files was made the default. One had to give it manually otherwise to process planet. With the change you cannot forget it.

**Comment by gefin** [comment]
The speed difference between old planet extractor files and your bayern.bin is real little. 
Its like 0.4sec to 0.3 sec while actual planet extracor is 3 to 4 seconds.
A actual maptool map render also in 0.3 sec . 

I must seek for old extractor files.
I did a crosscheck with Navit 0.5.1. where i used planet extractor files for long time without problems.
It showed near the same timing as the actual nightly build.

**Comment by metalstrolch** [comment]
I'll investigate. It shouldn't be that significant. I'm still not sure if the polygons created from multipolygons are really sorted into the right tile. Specially if item_order_by_type is honoured.

**Comment by metalstrolch** [comment]
OK. seems maptool is doing right in case of sorting. But I think I found the evil doers. There are some REALLY BIG multipolygons, in size and node count, that get shifted to the upper layers and therefore downloaded with every planet extractor excerpt. For America: the great lakes for example. For Europe: the Kaspian sea and some big deserts in Mongolia. While the total node count of them isn't the problem compared for e.g. Munich area, it's the memory usage as the nodes of those objects have to be processed at once (while Munich is processed object by object) And if your cache_size is too small, these nodes are read from file over and over again because they are processed even if not drawn at all. That's the reason devices with enough ram suffer way less from that.

@gefin, could you try to zoom out as much as possible and check for Kaspian sea (poly_water type) being present? You'll see it even in "world" view zoom.

Btw. Current trunk crashes because of g_alloca stack usage for draw preparation in graphics.c when trying to zoom at those objects. I'm preparing a fix for that.

**Comment by gefin** [comment]
@metalstrolch Yes i can see the Kaspian sea in the planetextractor bayern.bin also in World view.
B.t.w. i dont see a ocean.

What you write makes sens to me. Navit behave just like you write.

**Comment by metalstrolch** [comment]
OK. I'll try to chop those big polygons into pieces fitting to smaller tiles. This will have the drawback that those objects are not shown on world view any more, and depending of the drawing style (borders) you'll see the cut lines in rendering as Navit won't know that the object was chopped. But this seems to be the most feasible solution.

Somehow the same was done to the oceans, which makes them missing on world view as well. See https://trac.navit-project.org/ticket/854 for details on that. 

Deal with the crash on drawing: #897

**Comment by metalstrolch** [comment]
OK, finally it sems to be fixed. @gefin would you mind trying http://metalstrolche.de/bayern.bin ? This one is extracted from planet.bin created with #906 branch. You should find the big polygons like Kaspian Sea missing. And hopefully it renders almost as fast as the one created by only processing OSM excerpt of Bayern.

**Comment by gefin** [comment]
@metalstrolch  thanks, the Kaspian Sea is not in the map, the map renders well. No additional delays noticeable.
I see some blue rectangles wide outside the map region. The map Region is drawn well.

**Comment by metalstrolch** [comment]
The blue areas are the remains of another virtual flooding due to broken coastline. There some tiles get shifted up in the tile stack and therefore stay in the extracted map. Fortunately those are small in node count and don't affect speed and memory usage much. Maybe we should drop the coastline processing completely and use the coastline shapefiles instead. But that's another story.
