### ISSUE TITLE
maptool: unable to process the england map from osm

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#975]
Hi,

Trying to reproduce the issue https://bugs.debian.org/949780 that @clarified raised with maptool from the release 0.5.4 I tried with the england map (I have the same issue with the Great Britan one too) from https://download.geofabrik.de/europe/great-britain.html but I'm not able to produce the bin file from the protobuf.

I use the following command-line:
```
maptool --protobuf -i ~/Downloads/england-latest.osm.pbf test.bin > england-latest.log 2>&1
```

It fails with the error:
```
maptool: /build/navit-vwCTlu/navit-0.5.4+dfsg.1/navit/maptool/itembin.c:93: item_bin_copy_attr: Assertion `attr == attr_osm_wayid' failed.
```

**Question 1:** What would that error mean from the end user point of view? (someone unfamiliar with the code I mean, I know what an assert does, I'm talking more high level)

**Question 2:** There are also lots and lots of warnings during the processing. See attached file. Do any of those mean something meaningful?

The debian version is compiled with the following flags: https://salsa.debian.org/debian/navit/blob/master/debian/rules

**Question 3:** Are there any CMAKE flags that could cause it to break?

I'm testing also using the circleci version from [the latest build](https://circleci.com/gh/navit-gps/navit/19743#artifacts/containers/0) and can't reproduce the failure with this one.

Logs:
* [england-latest using the debian build](https://github.com/navit-gps/navit/files/4114263/england-latest-from-debian.log)
* [england-latest using the circleci build](https://github.com/navit-gps/navit/files/4114274/england-latest-from-circleci.log)

Thanks for your help,
Joseph

**Comment by clarified** [comment]
I have been trying with a copy of maptool compiled from git and often got assertion errors which turned out to be disk full problems. I was working in a RAM file to save wear on my SSDs, and found that I kept hitting assertion problems.

I have just bought a cheap 2nd hand spinning rust drive on which to experiment, and I have
now got a map.bin successfully generated. The log from that is attached, and has a large number of "Lost town" warnings which is worrying.

What I don't understand is some sort of non-deterministic behaviour: Although I was using the same maptool and pbf file, the generated "try_no_rule.bin" differed from another "test.bin" generated a few days ago. That test.bin was generated in a directory on an SSD. Since maptool seems to use worker threads in places, I suppose the different disc speeds and thermal throttling could involve different scheduling, and perhaps that could change the output order? Or it is as simple as a compilation datestamp being included in the generated map? But cmp seems to show extensive differences between the two outputs.

Disclaimer: I originated the debian bug report. And all this is closely related to #593 (Routing no longer possible on WinCE?)

But, of course, we need to know which, if any, of the messages in the log reports are important...

**Comment by clarified** [comment]
For some reason, I cannot attach files via github: "Something went really wrong, and we can't process that file". I have tried two browsers, and using firefox for this session. Hence the missing files from my previous comment.

**Comment by metalstrolch** [comment]
That usually means that github doesn't like your file type. It virtually only accepts zip, jpeg and png files. Not even plain .txt ones or tarballs.

The multithreaded parts of the maptool (some parts of the relation processing) produce indeterministic results as the thread scheduling affects the processing order. Disabling the threading by  -T 1 disables this. However the file dates are stored inside the .bin file. So two runs will never produce the exact same binary. If trying to bisect, you'll be better of unzipping the .bin file and compare the contents. However be warned that you cannot simply zip the files again to make a valid bin file, as navit's internal zip file support is very limited and your zip utility most likely does things navit doesn't support.

**Comment by clarified** [comment]
Thanks for that. I tried zipping up the log file into "norule.zip", but github refused that one as well with the same message :-(

Knowing that the bin outputs vary as you describe is useful. I haven't got around to actually testing any of them on wince as yet, but first I need to understand which warnings matter, if any.

**Comment by clarified** [comment]
I even tried a png file. But aerostitch seemed to be able to attach a plan text log file.
So why github is blocking all my files, I cannot tell.

**Comment by clarified** [comment]
As in #593, I now have maptool (from git) working with and without a "rule file". I get the same sort of errors as @aerostitch, although I can't attach them as above.

**Comment by clarified** [comment]
I have now solved the problem with attaching files: see #593. Here are the files:
[rule.log.gz](https://github.com/navit-gps/navit/files/4127468/rule.log.gz)
[no_rule.log.gz](https://github.com/navit-gps/navit/files/4127469/no_rule.log.gz)

**Comment by aerostitch** [comment]
Sorry I'm pretty much unavailable all the time these days with my new job.

Did you mean #953 ?

I still have the same issue using the latest Debian build and passing `-T1` to it.
There's no resources issues on my machine (the lowest my free disk space went was 75G).

Still not sure what flag could cause such discrepancy.

**Comment by pini-gh** [comment]
> Still not sure what flag could cause such discrepancy.

This is the '-DNDEBUG' compiler option set by the défault ('Release') build profile, but not by the Debian build configuration. From the assert(3) manpage:
> If the macro NDEBUG is defined at the moment <assert.h> was last included, the macro assert() generates no code, and hence does nothing at all

**Comment by kt3115a** [comment]
Hello. 
I have the same issue (maptool assertion failed on ubuntu, even with navit-daily ppa). I've followed the Navit build instruction and I have the navit binary as result, but no maptool. Please give me a hint how to build it separatelly.

Thanks

**Comment by mvglasow** [comment]
The original issue should be resolved by now (around early September, 2021); the fix was to remove the assertion. Can you verify it works now?

**Comment by jkoan** [comment]
Assuming it's working now
