### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by mvglasow** [navit-gps/navit#976]
Right now, Debian repos (including Raspbian and Ubuntu) have a Navit build based on <del>0.5.0, which is ~4 years old at this point</del> <del>Debian buster has 0.5.3, which is kinda OK given that 0.5.4 was only out recently, but still… Is there a way we could take care of Debianizing Navit by ourselves? I could imagine the folks over at Debian would be quite happy to see that happen.</del>

We could:
* <del>grab the .deb recipe files from Debian (if the license is compatible with GPLv2, else ask for permission)</del>
* <del>test them with current Navit and fix as needed</del>
* move the .deb recipe into the Navit source tree
* update CI to build the .deb package as part of the build (not only would this ensure the recipe still works, it would also give us a nice .deb package of each CI run)

<del>Once we get this to work, we could then sort out with the Debian maintainers how to get the current (i.e. last stable) version into the repos, and update it when we have a new release.</del>

If that works, we might think about RPM as well—but let’s tackle Debian first.

**Comment by mvglasow** [comment]
https://tracker.debian.org/pkg/navit shows me @aerostitch is on it already. Suppose the first two are solved, then… thanks for taking care of this.

That leaves me with two questions:
* what is Debian’s take on build recipes? Do they prefer to keep them separately, or can projects keep and maintain them in their source tree?
* in your opinion, can/should we build .deb packages as part of CI?

**Comment by aerostitch** [comment]
The recommended method by Debian is to do it separately. By default when updating the Debian package with a new release we filter out any upstream Debian folder.

The fact that buster has 0.5.3 is due to how the release cycle works in Debian. Basically a release like buster is a snapshot of the status of the packages in testing at the time of the release to ensure that the dependency are there and properly tested.
Ubuntu and other Debian derivatives generally take the .deb directly from the Debian testing or unstable repos.

We can build the .deb package every time in the CI but that is going to require more CI time. It really depends on the problem we are trying to solve.
I would personally advocate for shorter release cycles like once a month or once per quarter to get the changes in the repos quicker.

**Comment by okias** [comment]
```
[2020-05-09] navit 0.5.4+dfsg.1-4 MIGRATED to testing (Debian testing watch)
```
probably can be closed, seems to Debian has up-to-date version of Navit! :)
